image: ruby:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install jekyll bundler

pages:
  stage: deploy
  script:
  - jekyll build -d _site
  artifacts:
    paths:
    - _site
  only:
  - master
