title: NetSec Group conference tracker
description: Countdowns to top Security and Networking conference deadlines. 
author: Giacomo Giuliari

domain: "FIND A DOMAIN"
baseurl: ""

gitlab_repo: netsec-group-deadlines
gitlab_username: OU-PERRIG

markdown: kramdown

