title: NetSec Group conference tracker
description: Countdowns to top Security and Networking conference deadlines. 
author: Giacomo Giuliari

domain: "netsec-ethz.github.io"
baseurl: "/netsec-deadlines"

#gitlab_repo: netsec-group-deadlines
#gitlab_username: OU-PERRIG

github_repo: netsec-deadlines
github_username: giacgiuliari 

markdown: kramdown

